### ISSUE TITLE
boxShadow should not surround caption

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystemet#2025] opened 2024-05-16 09:21 UTC
![Image](https://github.com/digdir/designsystemet/assets/1464915/a2262aa5-c5b8-4632-baa5-69cf526ff948)

**Comment by Barsnes** [comment] 2024-05-21 08:40
This was fixed in #1987, and is a duplicate of #1985

**Closed** 2024-05-21 08:40 UTC
Labels: 🐛 bug, 🖥️ storefront
