### ISSUE TITLE
`Skeleton` no longer has correct text height

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystemet#2471] opened 2024-09-20 05:44 UTC
Currently:
https://next.storybook.designsystemet.no/?path=/docs/komponenter-loaders-skeleton--docs#text
![Image](https://github.com/user-attachments/assets/c10b0c87-95df-427e-bca7-79b0848254bd)

Before:
https://storybook.designsystemet.no/?path=/docs/komponenter-loaders-skeleton--docs#text
![Image](https://github.com/user-attachments/assets/dafbbdcd-4bbd-4011-b06f-1cec06c962a0)

**Comment by Barsnes** [comment] 2024-09-20 06:57
Is this a duplicate of #2468?

**Comment by mimarz** [comment] 2024-09-20 07:14
> Is this a duplicate of [#2468](https://github.com/digdir/designsystemet/issues/2468)?

Looks like, although that issue wasn't very descriptive of the problem? 🙈

**Comment by Barsnes** [comment] 2024-09-20 07:15
> > Is this a duplicate of [#2468](https://github.com/digdir/designsystemet/issues/2468)?
> 
> Looks like, although that issue wasn't very descriptive of the problem? 🙈

I agree, but let's delete one of them and update the remaining issue with what we need 🗡️

**Comment by eirikbacker** [comment] 2024-09-20 10:07
The solution we had before was to scale with vertical scale 60% which by accident worked with the font we have, but there is no guarantee for that, and the rounding was squished. However, it makes the elements the right height, and a 1:1 match with the content itself may not be possible with today's CSS text size units, so perhaps we should rather draw the content with ::before so the rounding is not squished, but we can still achieved 60% height? ☺️

**Comment by mimarz** [comment] 2024-09-20 12:46
Lets try that :)

**Closed** 2024-09-26 11:54 UTC
Labels: 🐛 bug, react, css
