### ISSUE TITLE
Combobox: Performance issue with re-rendering

### ISSUE THREAD

**Issue by Hifoz** [digdir/designsystemet#1765] opened 2024-04-05 12:15 UTC
### Description of the bug

Hi, we seem to have stumbeled over a performance-bug with the Combobox-component. 
We have a combobox with ~1800 items, and whenever it re-renders as a result of state-changes and re-rendering of a parent-component, it causes noticable lag, even though the combobox isnt even opened at the time.

Tried playing around a bit with the number of options in the combobox, and it seems like the time it needs to perform a rerender is proportional to the number of options. Virtualization of options-list also does not seem to affect this..

After som debugging, it appears that several of the useMemos in [useCombobox.tsx](https://github.com/digdir/designsystemet/blob/main/packages/react/src/components/form/Combobox/useCombobox.tsx), that only have `children` in their dependency-arrays runs on re-render, even though the children aren't getting changed

### Steps To Reproduce

.

### Additional Information

Codesandbox showing the effect of this issue: https://codesandbox.io/p/sandbox/bold-nightingale-f9d83p

**Comment by Barsnes** [comment] 2024-04-08 06:09
Hi, and thanks for the issue!
I believe this is a duplicate of #1516

**Closed** 2024-05-13 08:53 UTC
Labels: 🐛 bug
