### ISSUE TITLE
Correct aria usage on our HelpText component

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystemet#210] opened 2023-03-03 13:48 UTC
We are unsure on how we correctly use aria on our HelpText component. The component use our Popover component and is triggered by the user clicking a "?" icon. [Storybook](https://digdir.github.io/designsystem/?path=/docs/kjernekomponenter-helptext--help-text)

We had an issue where you couldnt reach the content of the HelpText with NVDA screen reader and the solution we found was to add `role:"tooltip"` But this is not in line with the [documentation](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role) or the [aria pattern](https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/). 

There are no "popover" role, so how de semanticly describe this correctly?

- [ ] Find similar examples from other design systems
- [ ] Find how this is used in the Altinn 3 cases today
- [ ] Find a way to describe this correctly, and make sure it is accessible

**Comment by mimarz** [comment] 2023-10-31 12:54
Can you test this @Thuneer ?

**Comment by mrosvik** [comment] 2024-01-30 11:31
Duplicate of #995

**Closed by mrosvik** 2024-01-30 11:31 UTC
Labels: ♿️ accessibility
